#if !defined(FCODER_LEX_GEN_HAND_WRITTEN_TYPES)
#define FCODER_LEX_GEN_HAND_WRITTEN_TYPES

struct Lexeme_Table_Value{
    Token_Base_Kind base_kind;
    u16 sub_kind;
};

struct Lexeme_Table_Lookup{
    b32 found_match;
    Token_Base_Kind base_kind;
    u16 sub_kind;
};

#endif
typedef u16 Token_Odin_Kind;
enum{
TokenOdinKind_EOF = 0,
TokenOdinKind_Whitespace = 1,
TokenOdinKind_LexError = 2,
TokenOdinKind_BlockComment = 3,
TokenOdinKind_LineComment = 4,
TokenOdinKind_Backslash = 5,
TokenOdinKind_LiteralInteger = 6,
TokenOdinKind_LiteralIntegerU = 7,
TokenOdinKind_LiteralIntegerL = 8,
TokenOdinKind_LiteralIntegerUL = 9,
TokenOdinKind_LiteralIntegerLL = 10,
TokenOdinKind_LiteralIntegerULL = 11,
TokenOdinKind_LiteralIntegerHex = 12,
TokenOdinKind_LiteralIntegerHexU = 13,
TokenOdinKind_LiteralIntegerHexL = 14,
TokenOdinKind_LiteralIntegerHexUL = 15,
TokenOdinKind_LiteralIntegerHexLL = 16,
TokenOdinKind_LiteralIntegerHexULL = 17,
TokenOdinKind_LiteralIntegerOct = 18,
TokenOdinKind_LiteralIntegerOctU = 19,
TokenOdinKind_LiteralIntegerOctL = 20,
TokenOdinKind_LiteralIntegerOctUL = 21,
TokenOdinKind_LiteralIntegerOctLL = 22,
TokenOdinKind_LiteralIntegerOctULL = 23,
TokenOdinKind_LiteralFloat32 = 24,
TokenOdinKind_LiteralFloat64 = 25,
TokenOdinKind_LiteralString = 26,
TokenOdinKind_LiteralStringWide = 27,
TokenOdinKind_LiteralStringUTF8 = 28,
TokenOdinKind_LiteralStringUTF16 = 29,
TokenOdinKind_LiteralStringUTF32 = 30,
TokenOdinKind_LiteralStringRaw = 31,
TokenOdinKind_LiteralStringWideRaw = 32,
TokenOdinKind_LiteralStringUTF8Raw = 33,
TokenOdinKind_LiteralStringUTF16Raw = 34,
TokenOdinKind_LiteralStringUTF32Raw = 35,
TokenOdinKind_LiteralCharacter = 36,
TokenOdinKind_LiteralCharacterWide = 37,
TokenOdinKind_LiteralCharacterUTF8 = 38,
TokenOdinKind_LiteralCharacterUTF16 = 39,
TokenOdinKind_LiteralCharacterUTF32 = 40,
TokenOdinKind_PPIncludeFile = 41,
TokenOdinKind_PPErrorMessage = 42,
TokenOdinKind_KeywordGeneric = 43,
TokenOdinKind_BraceOp = 44,
TokenOdinKind_BraceCl = 45,
TokenOdinKind_ParenOp = 46,
TokenOdinKind_BrackOp = 47,
TokenOdinKind_ParenCl = 48,
TokenOdinKind_BrackCl = 49,
TokenOdinKind_Semicolon = 50,
TokenOdinKind_Colon = 51,
TokenOdinKind_Range = 52,
TokenOdinKind_OpenRange = 53,
TokenOdinKind_ClosedRange = 54,
TokenOdinKind_ColonColon = 55,
TokenOdinKind_PlusPlus = 56,
TokenOdinKind_MinusMinus = 57,
TokenOdinKind_Dot = 58,
TokenOdinKind_Arrow = 59,
TokenOdinKind_Plus = 60,
TokenOdinKind_Minus = 61,
TokenOdinKind_Not = 62,
TokenOdinKind_Tilde = 63,
TokenOdinKind_Star = 64,
TokenOdinKind_And = 65,
TokenOdinKind_DotStar = 66,
TokenOdinKind_ArrowStar = 67,
TokenOdinKind_Div = 68,
TokenOdinKind_Mod = 69,
TokenOdinKind_LeftLeft = 70,
TokenOdinKind_RightRight = 71,
TokenOdinKind_Compare = 72,
TokenOdinKind_Less = 73,
TokenOdinKind_LessEq = 74,
TokenOdinKind_Grtr = 75,
TokenOdinKind_GrtrEq = 76,
TokenOdinKind_EqEq = 77,
TokenOdinKind_NotEq = 78,
TokenOdinKind_Xor = 79,
TokenOdinKind_Or = 80,
TokenOdinKind_AndAnd = 81,
TokenOdinKind_OrOr = 82,
TokenOdinKind_Ternary = 83,
TokenOdinKind_Eq = 84,
TokenOdinKind_PlusEq = 85,
TokenOdinKind_MinusEq = 86,
TokenOdinKind_StarEq = 87,
TokenOdinKind_DivEq = 88,
TokenOdinKind_ModEq = 89,
TokenOdinKind_LeftLeftEq = 90,
TokenOdinKind_RightRightEq = 91,
TokenOdinKind_Comma = 92,
TokenOdinKind_PPStringify = 93,
TokenOdinKind_PPConcat = 94,
TokenOdinKind_Void = 95,
TokenOdinKind_Bool = 96,
TokenOdinKind_Char = 97,
TokenOdinKind_Int = 98,
TokenOdinKind_Float = 99,
TokenOdinKind_Double = 100,
TokenOdinKind_Long = 101,
TokenOdinKind_Short = 102,
TokenOdinKind_Unsigned = 103,
TokenOdinKind_Signed = 104,
TokenOdinKind_Const = 105,
TokenOdinKind_Volatile = 106,
TokenOdinKind_Asm = 107,
TokenOdinKind_Break = 108,
TokenOdinKind_Case = 109,
TokenOdinKind_Catch = 110,
TokenOdinKind_Continue = 111,
TokenOdinKind_Default = 112,
TokenOdinKind_Do = 113,
TokenOdinKind_Else = 114,
TokenOdinKind_For = 115,
TokenOdinKind_Goto = 116,
TokenOdinKind_If = 117,
TokenOdinKind_Return = 118,
TokenOdinKind_Switch = 119,
TokenOdinKind_Try = 120,
TokenOdinKind_While = 121,
TokenOdinKind_StaticAssert = 122,
TokenOdinKind_ConstCast = 123,
TokenOdinKind_DynamicCast = 124,
TokenOdinKind_ReinterpretCast = 125,
TokenOdinKind_StaticCast = 126,
TokenOdinKind_Class = 127,
TokenOdinKind_Enum = 128,
TokenOdinKind_Struct = 129,
TokenOdinKind_Typedef = 130,
TokenOdinKind_Union = 131,
TokenOdinKind_Template = 132,
TokenOdinKind_Typename = 133,
TokenOdinKind_Friend = 134,
TokenOdinKind_Namespace = 135,
TokenOdinKind_Private = 136,
TokenOdinKind_Protected = 137,
TokenOdinKind_Public = 138,
TokenOdinKind_Using = 139,
TokenOdinKind_Extern = 140,
TokenOdinKind_Export = 141,
TokenOdinKind_Inline = 142,
TokenOdinKind_Static = 143,
TokenOdinKind_Virtual = 144,
TokenOdinKind_AlignAs = 145,
TokenOdinKind_Explicit = 146,
TokenOdinKind_NoExcept = 147,
TokenOdinKind_NullPtr = 148,
TokenOdinKind_Operator = 149,
TokenOdinKind_Register = 150,
TokenOdinKind_This = 151,
TokenOdinKind_ThreadLocal = 152,
TokenOdinKind_AlignOf = 153,
TokenOdinKind_DeclType = 154,
TokenOdinKind_TypeID = 155,
TokenOdinKind_New = 156,
TokenOdinKind_Delete = 157,
TokenOdinKind_b8 = 158,
TokenOdinKind_b16 = 159,
TokenOdinKind_b32 = 160,
TokenOdinKind_b64 = 161,
TokenOdinKind_i8 = 162,
TokenOdinKind_i16 = 163,
TokenOdinKind_i32 = 164,
TokenOdinKind_i64 = 165,
TokenOdinKind_i128 = 166,
TokenOdinKind_uint = 167,
TokenOdinKind_u8 = 168,
TokenOdinKind_u16 = 169,
TokenOdinKind_u32 = 170,
TokenOdinKind_u64 = 171,
TokenOdinKind_u128 = 172,
TokenOdinKind_i16le = 173,
TokenOdinKind_i32le = 174,
TokenOdinKind_i64le = 175,
TokenOdinKind_i128le = 176,
TokenOdinKind_u16le = 177,
TokenOdinKind_u32le = 178,
TokenOdinKind_u64le = 179,
TokenOdinKind_u128le = 180,
TokenOdinKind_i16be = 181,
TokenOdinKind_i32be = 182,
TokenOdinKind_i64be = 183,
TokenOdinKind_i128be = 184,
TokenOdinKind_u16be = 185,
TokenOdinKind_u32be = 186,
TokenOdinKind_u64be = 187,
TokenOdinKind_u128be = 188,
TokenOdinKind_f16 = 189,
TokenOdinKind_f32 = 190,
TokenOdinKind_f64 = 191,
TokenOdinKind_f16le = 192,
TokenOdinKind_f32le = 193,
TokenOdinKind_f64le = 194,
TokenOdinKind_f16be = 195,
TokenOdinKind_f32be = 196,
TokenOdinKind_f64be = 197,
TokenOdinKind_complex32 = 198,
TokenOdinKind_complex64 = 199,
TokenOdinKind_complex128 = 200,
TokenOdinKind_quaternion64 = 201,
TokenOdinKind_quaternion128 = 202,
TokenOdinKind_quaternion256 = 203,
TokenOdinKind_string = 204,
TokenOdinKind_cstring = 205,
TokenOdinKind_rawptr = 206,
TokenOdinKind_nil = 207,
TokenOdinKind_byte = 208,
TokenOdinKind_any = 209,
TokenOdinKind_package = 210,
TokenOdinKind_import = 211,
TokenOdinKind_foreign = 212,
TokenOdinKind_when = 213,
TokenOdinKind_defer = 214,
TokenOdinKind_in = 215,
TokenOdinKind_not_in = 216,
TokenOdinKind_or_else = 217,
TokenOdinKind_or_return = 218,
TokenOdinKind_fallthrough = 219,
TokenOdinKind_proc = 220,
TokenOdinKind_bit_field = 221,
TokenOdinKind_bit_set = 222,
TokenOdinKind_map = 223,
TokenOdinKind_dynamic = 224,
TokenOdinKind_cast = 225,
TokenOdinKind_auto_cast = 226,
TokenOdinKind_transmute = 227,
TokenOdinKind_no_inline = 228,
TokenOdinKind_context = 229,
TokenOdinKind_size_of = 230,
TokenOdinKind_align_of = 231,
TokenOdinKind_offset_of = 232,
TokenOdinKind_type_of = 233,
TokenOdinKind_distinct = 234,
TokenOdinKind_opaque = 235,
TokenOdinKind_LiteralTrue = 236,
TokenOdinKind_LiteralFalse = 237,
TokenOdinKind_Identifier = 238,
TokenOdinKind_PPInclude = 239,
TokenOdinKind_PPDefine = 240,
TokenOdinKind_PPUndef = 241,
TokenOdinKind_PPError = 242,
TokenOdinKind_PPUnknown = 243,
TokenOdinKind_COUNT = 244,
};
char *token_odin_kind_names[] = {
"EOF",
"Whitespace",
"LexError",
"BlockComment",
"LineComment",
"Backslash",
"LiteralInteger",
"LiteralIntegerU",
"LiteralIntegerL",
"LiteralIntegerUL",
"LiteralIntegerLL",
"LiteralIntegerULL",
"LiteralIntegerHex",
"LiteralIntegerHexU",
"LiteralIntegerHexL",
"LiteralIntegerHexUL",
"LiteralIntegerHexLL",
"LiteralIntegerHexULL",
"LiteralIntegerOct",
"LiteralIntegerOctU",
"LiteralIntegerOctL",
"LiteralIntegerOctUL",
"LiteralIntegerOctLL",
"LiteralIntegerOctULL",
"LiteralFloat32",
"LiteralFloat64",
"LiteralString",
"LiteralStringWide",
"LiteralStringUTF8",
"LiteralStringUTF16",
"LiteralStringUTF32",
"LiteralStringRaw",
"LiteralStringWideRaw",
"LiteralStringUTF8Raw",
"LiteralStringUTF16Raw",
"LiteralStringUTF32Raw",
"LiteralCharacter",
"LiteralCharacterWide",
"LiteralCharacterUTF8",
"LiteralCharacterUTF16",
"LiteralCharacterUTF32",
"PPIncludeFile",
"PPErrorMessage",
"KeywordGeneric",
"BraceOp",
"BraceCl",
"ParenOp",
"BrackOp",
"ParenCl",
"BrackCl",
"Semicolon",
"Colon",
"Range",
"OpenRange",
"ClosedRange",
"ColonColon",
"PlusPlus",
"MinusMinus",
"Dot",
"Arrow",
"Plus",
"Minus",
"Not",
"Tilde",
"Star",
"And",
"DotStar",
"ArrowStar",
"Div",
"Mod",
"LeftLeft",
"RightRight",
"Compare",
"Less",
"LessEq",
"Grtr",
"GrtrEq",
"EqEq",
"NotEq",
"Xor",
"Or",
"AndAnd",
"OrOr",
"Ternary",
"Eq",
"PlusEq",
"MinusEq",
"StarEq",
"DivEq",
"ModEq",
"LeftLeftEq",
"RightRightEq",
"Comma",
"PPStringify",
"PPConcat",
"Void",
"Bool",
"Char",
"Int",
"Float",
"Double",
"Long",
"Short",
"Unsigned",
"Signed",
"Const",
"Volatile",
"Asm",
"Break",
"Case",
"Catch",
"Continue",
"Default",
"Do",
"Else",
"For",
"Goto",
"If",
"Return",
"Switch",
"Try",
"While",
"StaticAssert",
"ConstCast",
"DynamicCast",
"ReinterpretCast",
"StaticCast",
"Class",
"Enum",
"Struct",
"Typedef",
"Union",
"Template",
"Typename",
"Friend",
"Namespace",
"Private",
"Protected",
"Public",
"Using",
"Extern",
"Export",
"Inline",
"Static",
"Virtual",
"AlignAs",
"Explicit",
"NoExcept",
"NullPtr",
"Operator",
"Register",
"This",
"ThreadLocal",
"AlignOf",
"DeclType",
"TypeID",
"New",
"Delete",
"b8",
"b16",
"b32",
"b64",
"i8",
"i16",
"i32",
"i64",
"i128",
"uint",
"u8",
"u16",
"u32",
"u64",
"u128",
"i16le",
"i32le",
"i64le",
"i128le",
"u16le",
"u32le",
"u64le",
"u128le",
"i16be",
"i32be",
"i64be",
"i128be",
"u16be",
"u32be",
"u64be",
"u128be",
"f16",
"f32",
"f64",
"f16le",
"f32le",
"f64le",
"f16be",
"f32be",
"f64be",
"complex32",
"complex64",
"complex128",
"quaternion64",
"quaternion128",
"quaternion256",
"string",
"cstring",
"rawptr",
"nil",
"byte",
"any",
"package",
"import",
"foreign",
"when",
"defer",
"in",
"not_in",
"or_else",
"or_return",
"fallthrough",
"proc",
"bit_field",
"bit_set",
"map",
"dynamic",
"cast",
"auto_cast",
"transmute",
"no_inline",
"context",
"size_of",
"align_of",
"offset_of",
"type_of",
"distinct",
"opaque",
"LiteralTrue",
"LiteralFalse",
"Identifier",
"PPInclude",
"PPDefine",
"PPUndef",
"PPError",
"PPUnknown",
};
